# Generated by Django 5.2.8 on 2025-11-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitarAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('setor', models.CharField(blank=True, max_length=200, verbose_name='Setor')),
                ('motivo', models.TextField(verbose_name='Motivo do acesso')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('negado', 'Negado')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da solicitação')),
                ('data_decisao', models.DateTimeField(blank=True, null=True, verbose_name='Data da decisão')),
                ('observacao_admin', models.TextField(blank=True, verbose_name='Observação do administrador')),
            ],
            options={
                'verbose_name': 'Solicitação de acesso',
                'verbose_name_plural': 'Solicitações de acesso',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
