# Generated by Django 5.2.8 on 2025-11-27 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=20, verbose_name='Status anterior')),
                ('status_novo', models.CharField(blank=True, max_length=20, verbose_name='Status novo')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data do registro')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='solicitacoes.solicitaracesso', verbose_name='Solicitação')),
                ('usuario_criado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_usuarios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário criado')),
                ('usuario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_solicitacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável')),
            ],
            options={
                'verbose_name': 'Auditoria de solicitação',
                'verbose_name_plural': 'Auditorias de solicitação',
                'ordering': ['-data_registro'],
            },
        ),
    ]
