# Generated by Django 5.2.8 on 2025-12-08 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Papel', 'verbose_name_plural': 'Papéis'},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'verbose_name': 'Permissão de Papel', 'verbose_name_plural': 'Permissões de Papéis'},
        ),
        migrations.AlterModelOptions(
            name='solicitacaoacesso',
            options={'verbose_name': 'Solicitação de Acesso', 'verbose_name_plural': 'Solicitações de Acesso'},
        ),
        migrations.AlterModelOptions(
            name='userconfig',
            options={'verbose_name': 'Configuração do Usuário', 'verbose_name_plural': 'Configurações dos Usuários'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'Vínculo Usuário → Papel', 'verbose_name_plural': 'Vínculos Usuários → Papéis'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
