# Generated by Django 5.2.8 on 2026-08-17 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carimbos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='distribuicaocopia',
            name='entregue_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='distribuicaocopia',
            name='entregue_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copias_controladas_entregues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distribuicaocopia',
            name='meio_distribuicao',
            field=models.CharField(choices=[('NAO_INFORMADO', 'Não informado'), ('FISICO', 'Cópia física'), ('DIGITAL', 'Cópia digital')], db_index=True, default='NAO_INFORMADO', max_length=20),
        ),
        migrations.AddField(
            model_name='distribuicaocopia',
            name='quantidade',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='distribuicaocopia',
            name='recebedor_carimbo',
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='distribuicaocopia',
            name='status',
            field=models.CharField(choices=[('EMITIDA', 'Cópia gerada / entrega não confirmada'), ('ENTREGUE', 'Entrega confirmada'), ('RECOLHIMENTO_PENDENTE', 'Recolhimento pendente'), ('RECOLHIDA', 'Recolhida'), ('SUBSTITUIDA', 'Substituída'), ('CANCELADA', 'Cancelada'), ('EXTRAVIADA', 'Extraviada/justificada')], db_index=True, default='EMITIDA', max_length=40),
        ),
    ]
