# Generated by Django 5.2.8 on 2026-05-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoAutomacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(default='iniciado', max_length=30)),
                ('mensagem', models.TextField(blank=True)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransmittalKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(blank=True, max_length=100)),
                ('titulo', models.TextField(blank=True)),
                ('pasta', models.CharField(blank=True, max_length=255)),
                ('emissao', models.CharField(blank=True, max_length=100)),
                ('proposito_emissao', models.CharField(blank=True, max_length=150)),
                ('data_envio', models.CharField(blank=True, max_length=20)),
                ('transmittal_numero', models.CharField(blank=True, max_length=100)),
                ('arquivo_pdf', models.TextField(blank=True)),
                ('status_parse', models.CharField(blank=True, max_length=50)),
                ('observacao_parse', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['documento'],
                'unique_together': {('documento', 'transmittal_numero')},
            },
        ),
    ]
