# Generated by Django 5.2.8 on 2026-05-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCFTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('caminho', models.TextField(blank=True)),
                ('pcf_link', models.CharField(blank=True, max_length=255)),
                ('numero_pcf', models.CharField(blank=True, max_length=255)),
                ('numero_documento', models.CharField(blank=True, max_length=255)),
                ('titulo', models.TextField(blank=True)),
                ('revisao_pcf', models.CharField(blank=True, max_length=50)),
                ('data_recebimento', models.CharField(blank=True, max_length=50)),
                ('open_comments', models.IntegerField(default=0)),
                ('qtd_comentarios', models.IntegerField(default=0)),
                ('status_final', models.CharField(blank=True, max_length=255)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['numero_documento', 'revisao_pcf'],
                'unique_together': {('tipo', 'numero_documento', 'revisao_pcf', 'pcf_link')},
            },
        ),
    ]
