# Generated by Django 5.2.8 on 2026-05-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0002_pcftimeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(blank=True, max_length=255)),
                ('revisao', models.CharField(blank=True, max_length=50)),
                ('titulo', models.TextField(blank=True)),
                ('disciplina', models.CharField(blank=True, max_length=100)),
                ('status_documento', models.CharField(blank=True, max_length=100)),
                ('status_grd', models.CharField(blank=True, max_length=100)),
                ('grd', models.CharField(blank=True, max_length=255)),
                ('data_grd', models.CharField(blank=True, max_length=50)),
                ('pcf', models.CharField(blank=True, max_length=255)),
                ('data_pcf', models.CharField(blank=True, max_length=50)),
                ('status_final_pcf', models.CharField(blank=True, max_length=255)),
                ('pcf_resposta', models.CharField(blank=True, max_length=255)),
                ('data_resposta', models.CharField(blank=True, max_length=50)),
                ('grd_resposta', models.CharField(blank=True, max_length=255)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['documento', 'revisao'],
                'unique_together': {('documento', 'revisao')},
            },
        ),
    ]
