# Generated by Django 5.2.8 on 2026-05-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0003_documentold'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentold',
            name='caminho_documento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentold',
            name='caminho_grd',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentold',
            name='caminho_grd_resposta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentold',
            name='caminho_pcf',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentold',
            name='caminho_resposta',
            field=models.TextField(blank=True),
        ),
    ]
