# Generated by Django 5.2.8 on 2026-05-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0004_documentold_caminho_documento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentold',
            options={'ordering': ['origem_aba', 'documento', 'revisao']},
        ),
        migrations.AlterUniqueTogether(
            name='documentold',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='documentold',
            name='origem_aba',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='documentold',
            unique_together={('origem_aba', 'documento', 'revisao')},
        ),
    ]
