# Generated by Django 5.2.8 on 2026-05-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0005_alter_documentold_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentold',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='documentold',
            constraint=models.UniqueConstraint(fields=('origem_aba', 'documento', 'revisao'), name='uniq_documentold_origem_documento_revisao'),
        ),
    ]
