# Generated by Django 5.2.8 on 2026-05-11 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0006_alter_documentold_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execucaoautomacao',
            options={'ordering': ['-iniciado_em'], 'verbose_name': 'Execução de automação', 'verbose_name_plural': 'Execuções de automações'},
        ),
        migrations.AddField(
            model_name='execucaoautomacao',
            name='detalhes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='execucaoautomacao',
            name='duracao_segundos',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='execucaoautomacao',
            name='quantidade_processada',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='execucaoautomacao',
            name='sucesso',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='execucaoautomacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_automacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='execucaoautomacao',
            name='iniciado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='execucaoautomacao',
            name='status',
            field=models.CharField(choices=[('iniciado', 'Iniciado'), ('sucesso', 'Sucesso'), ('erro', 'Erro')], db_index=True, default='iniciado', max_length=30),
        ),
    ]
