# Generated by Django 5.2.8 on 2026-05-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0007_alter_execucaoautomacao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucaoautomacao',
            name='status',
            field=models.CharField(choices=[('iniciado', 'Iniciado'), ('processando', 'Processando'), ('sucesso', 'Sucesso'), ('sucesso_parcial', 'Sucesso parcial'), ('erro', 'Erro'), ('cancelado', 'Cancelado')], db_index=True, default='iniciado', max_length=30),
        ),
    ]
