# Generated by Django 5.2.8 on 2026-05-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0008_alter_execucaoautomacao_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='KMFileIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=500)),
                ('caminho_completo', models.TextField(unique=True)),
                ('pasta', models.TextField(blank=True)),
                ('extensao', models.CharField(blank=True, db_index=True, max_length=20)),
                ('tamanho_bytes', models.BigIntegerField(default=0)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
                ('nome_normalizado', models.CharField(blank=True, db_index=True, max_length=600)),
                ('stem_normalizado', models.CharField(blank=True, db_index=True, max_length=600)),
                ('documento_extraido', models.CharField(blank=True, db_index=True, max_length=255)),
                ('eh_transmittal_letter', models.BooleanField(db_index=True, default=False)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('indexado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Índice de arquivo KM',
                'verbose_name_plural': 'Índice de arquivos KM',
                'ordering': ['nome_arquivo'],
                'indexes': [models.Index(fields=['ativo', 'extensao'], name='automacoes__ativo_3cc008_idx'), models.Index(fields=['ativo', 'eh_transmittal_letter'], name='automacoes__ativo_2114b3_idx'), models.Index(fields=['documento_extraido'], name='automacoes__documen_6b2c38_idx')],
            },
        ),
    ]
