# Generated by GED Engineering on 2026-05-13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("automacoes", "0009_kmfileindex"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("termo", models.CharField(db_index=True, max_length=500)),
                ("tipo", models.CharField(blank=True, db_index=True, default="todos", max_length=50)),
                (
                    "origem",
                    models.CharField(
                        choices=[("web", "Web"), ("api", "API")],
                        db_index=True,
                        default="web",
                        max_length=30,
                    ),
                ),
                ("total_geral", models.PositiveIntegerField(default=0)),
                ("total_km", models.PositiveIntegerField(default=0)),
                ("total_transmittals", models.PositiveIntegerField(default=0)),
                ("total_ld", models.PositiveIntegerField(default=0)),
                ("total_pcfs", models.PositiveIntegerField(default=0)),
                ("duracao_ms", models.PositiveIntegerField(default=0)),
                ("sucesso", models.BooleanField(db_index=True, default=True)),
                ("mensagem", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="buscas_ged",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoria de busca GED",
                "verbose_name_plural": "Auditorias de busca GED",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(fields=["termo", "tipo"], name="automacoes__termo_5e0e8c_idx"),
                    models.Index(fields=["origem", "criado_em"], name="automacoes__origem_0b6e31_idx"),
                    models.Index(fields=["sucesso", "criado_em"], name="automacoes__sucesso_9bb83d_idx"),
                ],
            },
        ),
    ]
