# Generated by Django 5.2.8 on 2026-05-13 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0011_jobexecution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobexecution',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='jobexecution',
            new_name='automacoes__job_nam_168776_idx',
            old_name='automacoes_job_name_status_idx',
        ),
        migrations.RenameIndex(
            model_name='jobexecution',
            new_name='automacoes__status_0618cc_idx',
            old_name='automacoes_job_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='searchaudit',
            new_name='automacoes__termo_5c3bf9_idx',
            old_name='automacoes__termo_5e0e8c_idx',
        ),
        migrations.RenameIndex(
            model_name='searchaudit',
            new_name='automacoes__origem_00ffad_idx',
            old_name='automacoes__origem_0b6e31_idx',
        ),
        migrations.RenameIndex(
            model_name='searchaudit',
            new_name='automacoes__sucesso_25eb8c_idx',
            old_name='automacoes__sucesso_9bb83d_idx',
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='job_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
