# Generated by Django 5.2.8 on 2026-05-13 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0013_schedulerstate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='schedulerstate',
            new_name='automacoes__enabled_a00976_idx',
            old_name='automacoes__enabled_2d3166_idx',
        ),
        migrations.RenameIndex(
            model_name='schedulerstate',
            new_name='automacoes__heartbe_0451d1_idx',
            old_name='automacoes__heartbe_7a2fd7_idx',
        ),
        migrations.RenameIndex(
            model_name='schedulerstate',
            new_name='automacoes__next_ru_0e0916_idx',
            old_name='automacoes__next_ru_2ba60b_idx',
        ),
    ]
