# Generated by Django 5.2.8 on 2026-05-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0015_runtimealert'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='runtimealert',
            new_name='automacoes__codigo_2be742_idx',
            old_name='automacoes__codigo_runtime_idx',
        ),
        migrations.RenameIndex(
            model_name='runtimealert',
            new_name='automacoes__severid_aecdff_idx',
            old_name='automacoes__severity_runtime_idx',
        ),
    ]
