# Generated by Django 5.2.8 on 2026-05-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0016_alter_jobexecution_payload_alter_jobexecution_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='manual', max_length=40)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('runtime_score', models.PositiveSmallIntegerField(default=0)),
                ('runtime_status', models.CharField(default='unknown', max_length=30)),
                ('active_alerts', models.PositiveIntegerField(default=0)),
                ('failed_jobs', models.PositiveIntegerField(default=0)),
                ('running_jobs', models.PositiveIntegerField(default=0)),
                ('stale_scheduler_states', models.PositiveIntegerField(default=0)),
                ('jobs_today', models.PositiveIntegerField(default=0)),
                ('success_today', models.PositiveIntegerField(default=0)),
                ('failed_today', models.PositiveIntegerField(default=0)),
                ('success_rate', models.FloatField(default=0)),
                ('avg_duration', models.FloatField(blank=True, null=True)),
                ('scheduler_total', models.PositiveIntegerField(default=0)),
                ('scheduler_enabled', models.PositiveIntegerField(default=0)),
                ('scheduler_disabled', models.PositiveIntegerField(default=0)),
                ('total_jobs', models.PositiveIntegerField(default=0)),
                ('total_alerts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Runtime Metric Snapshot',
                'verbose_name_plural': 'Runtime Metric Snapshots',
                'ordering': ['-captured_at'],
            },
        ),
    ]
