# Generated by Django 5.2.8 on 2026-05-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0017_runtimemetricsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentold',
            name='arquivo_km_encontrado',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica se o arquivo físico KM foi localizado no índice de rede.'),
        ),
        migrations.AddField(
            model_name='documentold',
            name='data_recebimento_km',
            field=models.CharField(blank=True, help_text='Data de recebimento do documento via transmittal KM.', max_length=50),
        ),
        migrations.AddField(
            model_name='documentold',
            name='numero_documento_km',
            field=models.CharField(blank=True, db_index=True, help_text='Número do documento KM vinculado ao documento Petrobras/Transpetro.', max_length=255),
        ),
        migrations.AddField(
            model_name='documentold',
            name='observacao_vinculo_km',
            field=models.TextField(blank=True, help_text='Observações operacionais do motor de vínculo KM ↔ LD.'),
        ),
        migrations.AddField(
            model_name='documentold',
            name='score_vinculo_km',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Pontuação de confiança do vínculo KM ↔ LD, de 0 a 100.'),
        ),
        migrations.AddField(
            model_name='documentold',
            name='status_vinculo_km',
            field=models.CharField(choices=[('AUTO', 'Vinculado automaticamente'), ('MANUAL', 'Vinculado manualmente'), ('PENDENTE', 'Pendente'), ('CONFLITO', 'Conflito'), ('SEM_MATCH', 'Sem correspondência'), ('MULTIPLO', 'Múltiplas correspondências')], db_index=True, default='PENDENTE', help_text='Status do vínculo entre o documento KM e a LD Petrobras.', max_length=30),
        ),
        migrations.AddField(
            model_name='documentold',
            name='transmittal_km',
            field=models.CharField(blank=True, db_index=True, help_text='Último transmittal KM relacionado a este documento.', max_length=100),
        ),
        migrations.AddIndex(
            model_name='documentold',
            index=models.Index(fields=['origem_aba', 'numero_documento_km'], name='automacoes__origem__20e201_idx'),
        ),
        migrations.AddIndex(
            model_name='documentold',
            index=models.Index(fields=['status_vinculo_km', 'score_vinculo_km'], name='automacoes__status__915757_idx'),
        ),
        migrations.AddIndex(
            model_name='documentold',
            index=models.Index(fields=['transmittal_km'], name='automacoes__transmi_faca05_idx'),
        ),
    ]
