# Generated by Django 5.2.8 on 2026-05-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0018_documentold_arquivo_km_encontrado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentold',
            name='observacao_revisao_km',
            field=models.TextField(blank=True, help_text='Observações da comparação de revisão KM ↔ LD.'),
        ),
        migrations.AddField(
            model_name='documentold',
            name='revisao_km',
            field=models.CharField(blank=True, db_index=True, help_text='Revisão identificada no recebimento KM/transmittal.', max_length=50),
        ),
        migrations.AddField(
            model_name='documentold',
            name='status_revisao_km',
            field=models.CharField(choices=[('OK', 'Revisão compatível'), ('DIVERGENTE', 'Revisão divergente'), ('PENDENTE', 'Revisão pendente'), ('SEM_REVISAO', 'Sem revisão KM')], db_index=True, default='PENDENTE', help_text='Status comparativo entre revisão KM e revisão LD/Petrobras.', max_length=30),
        ),
        migrations.AddIndex(
            model_name='documentold',
            index=models.Index(fields=['status_revisao_km', 'revisao_km'], name='automacoes__status__e81d13_idx'),
        ),
    ]
