# Generated by Django 5.2.8 on 2026-05-18 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0019_documentold_observacao_revisao_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_km', models.CharField(db_index=True, help_text='Número do documento Kongsberg/KM.', max_length=255, unique=True)),
                ('titulo', models.TextField(blank=True)),
                ('disciplina', models.CharField(blank=True, db_index=True, max_length=120)),
                ('toc', models.CharField(blank=True, max_length=120)),
                ('phase', models.CharField(blank=True, max_length=120)),
                ('responsible', models.CharField(blank=True, max_length=255)),
                ('contractual_delivery', models.CharField(blank=True, max_length=80)),
                ('first_delivery', models.CharField(blank=True, max_length=80)),
                ('status_km', models.CharField(blank=True, db_index=True, max_length=120)),
                ('revisao_km', models.CharField(blank=True, db_index=True, max_length=50)),
                ('status_recebimento', models.CharField(choices=[('RECEBIDO', 'Recebido da Kongsberg'), ('PENDENTE', 'Pendente de recebimento')], db_index=True, default='PENDENTE', max_length=30)),
                ('transmittal_numero', models.CharField(blank=True, db_index=True, max_length=120)),
                ('data_recebimento_km', models.CharField(blank=True, max_length=80)),
                ('documento_tp', models.CharField(blank=True, db_index=True, help_text='Número Petrobras/Transpetro associado ao documento KM.', max_length=255)),
                ('status_vinculo_ld', models.CharField(choices=[('AUTO', 'Vinculado automaticamente'), ('MANUAL', 'Vinculado manualmente'), ('PENDENTE', 'Pendente'), ('CONFLITO', 'Conflito'), ('SEM_MATCH', 'Sem correspondência'), ('MULTIPLO', 'Múltiplas correspondências')], db_index=True, default='PENDENTE', max_length=30)),
                ('score_vinculo_ld', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('observacao_vinculo_ld', models.TextField(blank=True)),
                ('arquivo_km_encontrado', models.BooleanField(db_index=True, default=False)),
                ('caminho_km', models.TextField(blank=True)),
                ('origem_planilha', models.CharField(blank=True, max_length=255)),
                ('linha_origem', models.PositiveIntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('documento_ld', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_km', to='automacoes.documentold')),
            ],
            options={
                'verbose_name': 'Documento KM',
                'verbose_name_plural': 'Documentos KM',
                'ordering': ['numero_km'],
                'indexes': [models.Index(fields=['status_recebimento', 'status_vinculo_ld'], name='automacoes__status__8e01e2_idx'), models.Index(fields=['disciplina', 'status_km'], name='automacoes__discipl_5bbd2d_idx'), models.Index(fields=['documento_tp'], name='automacoes__documen_193442_idx'), models.Index(fields=['transmittal_numero'], name='automacoes__transmi_b4096f_idx'), models.Index(fields=['arquivo_km_encontrado'], name='automacoes__arquivo_1310e7_idx')],
            },
        ),
    ]
