# Generated by Django 5.2.8 on 2026-05-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0020_documentokm'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentokm',
            name='agreed_delivery',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='documentokm',
            name='core_share_document',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentokm',
            name='core_share_folder',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentokm',
            name='preliminary_delivery',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='documentokm',
            name='released_for',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
