# Generated by Django 5.2.8 on 2026-06-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0021_documentokm_agreed_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentold',
            name='action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentold',
            name='casco',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentold',
            name='nb_pending_comments',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='documentold',
            name='numero_interno',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documentold',
            name='open_comments',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='documentold',
            name='posted_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='documentold',
            name='qtd_comentarios',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='documentold',
            name='resp_for_issue',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documentold',
            name='since',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentold',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documentold',
            name='under_review',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
