# Generated by Django 5.2.8 on 2026-08-13 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0024_automationexecutionlock'),
        ('documentos', '0019_documentoreferenciaexterna'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentold',
            name='documento_ged',
            field=models.ForeignKey(blank=True, help_text='Documento central do GED correspondente a esta linha/revisão da LD.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_ld', to='documentos.documento'),
        ),
    ]
