# Generated by Django 5.2.8 on 2026-08-14 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0025_documentold_documento_ged'),
        ('documentos', '0020_documentoreferenciaexterna_conferido_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pcftimeline',
            name='documento_ged',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcfs_timeline', to='documentos.documento'),
        ),
        migrations.AddField(
            model_name='transmittalkm',
            name='documento_ged',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transmittals_km', to='documentos.documento'),
        ),
        migrations.CreateModel(
            name='PendenciaDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=300, unique=True)),
                ('tipo', models.CharField(db_index=True, max_length=80)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('acao_recomendada', models.TextField(blank=True)),
                ('origem', models.CharField(blank=True, db_index=True, max_length=50)),
                ('severidade', models.CharField(choices=[('INFO', 'Informativa'), ('ATENCAO', 'Atenção'), ('CRITICA', 'Crítica')], db_index=True, default='ATENCAO', max_length=20)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_TRATAMENTO', 'Em tratamento'), ('RESOLVIDA', 'Resolvida')], db_index=True, default='ABERTA', max_length=20)),
                ('responsavel_texto', models.CharField(blank=True, max_length=255)),
                ('prazo', models.DateField(blank=True, db_index=True, null=True)),
                ('detectada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('resolvida_em', models.DateTimeField(blank=True, null=True)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='documentos.documento')),
                ('registro_ld', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendencias', to='automacoes.documentold')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendencias_documentais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-severidade', 'prazo', 'documento__codigo'],
                'indexes': [models.Index(fields=['status', 'severidade'], name='automacoes__status_a2818a_idx'), models.Index(fields=['tipo', 'origem'], name='automacoes__tipo_4f09f4_idx')],
            },
        ),
    ]
