# Generated by Django 5.2.8 on 2025-11-17 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(blank=True, max_length=100, null=True)),
                ('fase', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(max_length=200)),
                ('revisao', models.CharField(default='0', max_length=10)),
                ('disciplina', models.CharField(blank=True, max_length=50, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('status_ldp', models.CharField(blank=True, max_length=50, null=True)),
                ('status_emissao', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_grdt', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_pcf', models.CharField(blank=True, max_length=50, null=True)),
                ('data_emissao_tp', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportacaoLDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('total_sucesso', models.IntegerField(default=0)),
                ('total_erros', models.IntegerField(default=0)),
                ('log', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsavelDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=50, unique=True)),
                ('responsavel', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArquivoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos/anexos/')),
                ('nome_original', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='documentos.documento')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='documentos.documento')),
            ],
        ),
    ]
