# Generated by Django 5.2.8 on 2025-11-24 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_ativo_documento_deletado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoVersao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_revisao', models.CharField(help_text='Número da revisão (ex: R0, R1, A, B, C)', max_length=10)),
                ('arquivo', models.FileField(upload_to='documentos/versoes/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, help_text='Descrição das alterações desta revisão')),
                ('status_revisao', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('REVISAO', 'Em Revisão'), ('APROVADO', 'Aprovado'), ('CANCELADO', 'Cancelado')], default='REVISAO', max_length=20)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='documentos.documento')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
