# Generated by Django 5.2.8 on 2025-11-25 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documentos', '0003_documentoversao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoversao',
            name='numero_revisao',
            field=models.CharField(help_text='Número da revisão (ex: 0, 1, A, B, C)', max_length=10),
        ),
        migrations.CreateModel(
            name='WorkflowEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(help_text='Ordem do fluxo (1, 2, 3...)')),
                ('prazo_dias', models.PositiveIntegerField(default=0, help_text='Prazo em dias para conclusão desta etapa (0 = sem prazo)')),
                ('ativa', models.BooleanField(default=True)),
                ('grupos_responsaveis', models.ManyToManyField(blank=True, related_name='etapas_workflow', to='auth.group')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoWorkflowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True, help_text='Início da etapa atual')),
                ('prazo_final', models.DateTimeField(blank=True, help_text='Data/hora limite calculada em função do prazo da etapa', null=True)),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_status', to='documentos.documento')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='documentos.workflowetapa')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('COMENTADO', 'Comentado')], default='PENDENTE', max_length=20)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprovacoes', to='documentos.documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprovacoes_documentos', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprovacoes', to='documentos.workflowetapa')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
