# Generated by Django 5.2.8 on 2025-11-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_alter_documentoversao_numero_revisao_workflowetapa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='etapa_atual',
            field=models.CharField(default='Revisão Interna – Disciplina', max_length=100),
        ),
    ]
