# Generated by Django 5.2.8 on 2025-11-29 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documentos', '0005_documento_etapa_atual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('cliente', models.CharField(blank=True, max_length=120, null=True)),
                ('pasta_base', models.CharField(help_text='Caminho base na rede onde serão criadas as pastas de saída (GRDT, GED, etc.)', max_length=500)),
                ('prefixo_ged', models.CharField(default='GED', help_text='Prefixo padrão para numeração de GED interna (ex: GED, GD, DC, etc.)', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.DeleteModel(
            name='ImportacaoLDP',
        ),
        migrations.AlterModelOptions(
            name='arquivodocumento',
            options={'ordering': ['-enviado_em'], 'verbose_name': 'Arquivo do Documento', 'verbose_name_plural': 'Arquivos do Documento'},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['codigo', 'revisao'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='documentoaprovacao',
            options={'ordering': ['-data'], 'verbose_name': 'Aprovação de Documento', 'verbose_name_plural': 'Aprovações de Documentos'},
        ),
        migrations.AlterModelOptions(
            name='documentoversao',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Versão do Documento', 'verbose_name_plural': 'Versões do Documento'},
        ),
        migrations.AlterModelOptions(
            name='documentoworkflowstatus',
            options={'verbose_name': 'Status do Workflow do Documento', 'verbose_name_plural': 'Status do Workflow dos Documentos'},
        ),
        migrations.AlterModelOptions(
            name='responsaveldisciplina',
            options={'ordering': ['disciplina'], 'verbose_name': 'Responsável por Disciplina', 'verbose_name_plural': 'Responsáveis por Disciplina'},
        ),
        migrations.AlterModelOptions(
            name='workflowetapa',
            options={'ordering': ['ordem'], 'verbose_name': 'Etapa de Workflow', 'verbose_name_plural': 'Etapas de Workflow'},
        ),
        migrations.RemoveField(
            model_name='documento',
            name='data_emissao_tp',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='numero_grdt',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='numero_pcf',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='status_ldp',
        ),
        migrations.AddField(
            model_name='documento',
            name='data_emissao_grdt',
            field=models.DateField(blank=True, null=True, verbose_name='Data Emissão GRDT'),
        ),
        migrations.AddField(
            model_name='documento',
            name='ged_interna',
            field=models.CharField(blank=True, help_text='Identificação interna da GED gerada para este documento (quando aplicável)', max_length=50, null=True, verbose_name='GED Interna'),
        ),
        migrations.AddField(
            model_name='documento',
            name='grdt_cliente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GRDT Cliente'),
        ),
        migrations.AddField(
            model_name='documento',
            name='resposta_cliente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Resposta Cliente'),
        ),
        migrations.AddField(
            model_name='documento',
            name='status_documento',
            field=models.CharField(blank=True, help_text="Substitui o antigo 'Status LDP'", max_length=50, null=True, verbose_name='Status do Documento'),
        ),
        migrations.AlterField(
            model_name='arquivodocumento',
            name='tipo',
            field=models.CharField(blank=True, help_text='Classificação opcional do anexo (PDF, DWG, DOCX, etc.)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='status_emissao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status de Emissão'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_doc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='workflowetapa',
            name='grupos_responsaveis',
            field=models.ManyToManyField(blank=True, help_text='Grupos de usuários responsáveis por atuar nesta etapa', related_name='etapas_workflow', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='documentos.projeto'),
        ),
        migrations.DeleteModel(
            name='WorkflowDocumento',
        ),
    ]
