# Generated by Django 5.2.8 on 2025-12-04 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_alter_documentoaprovacao_options_logauditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(max_length=50)),
                ('valor_total_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('moeda', models.CharField(default='USD', max_length=10)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro', to='documentos.projeto')),
            ],
        ),
    ]
