# Generated by Django 5.2.8 on 2025-12-05 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documentos', '0008_projetofinanceiro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivodocumento',
            options={'ordering': ['-enviado_em']},
        ),
        migrations.AlterModelOptions(
            name='documentoversao',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AlterModelOptions(
            name='documentoworkflowstatus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='logauditoria',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='responsaveldisciplina',
            options={'ordering': ['disciplina']},
        ),
        migrations.AlterModelOptions(
            name='workflowetapa',
            options={'ordering': ['ordem']},
        ),
        migrations.AddField(
            model_name='documento',
            name='valor_brl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor (R$)'),
        ),
        migrations.AddField(
            model_name='documento',
            name='valor_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor (USD)'),
        ),
        migrations.AlterField(
            model_name='arquivodocumento',
            name='tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='ged_interna',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='grdt_cliente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='resposta_cliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='status_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='status_emissao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documentoversao',
            name='numero_revisao',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='documentoversao',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentoworkflowstatus',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.workflowetapa'),
        ),
        migrations.AlterField(
            model_name='documentoworkflowstatus',
            name='iniciado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documentoworkflowstatus',
            name='prazo_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='pasta_base',
            field=models.CharField(help_text='Caminho base na rede onde serão criadas as pastas de saída (GRDT/GED)', max_length=500),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='prefixo_ged',
            field=models.CharField(default='GED', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowetapa',
            name='grupos_responsaveis',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='workflowetapa',
            name='ordem',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='workflowetapa',
            name='prazo_dias',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='DocumentoAprovacao',
        ),
    ]
