# Generated by Django 5.2.8 on 2025-12-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0010_finance_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='valor_brl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor (R$)'),
        ),
        migrations.AlterField(
            model_name='projetofinanceiro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projetofinanceiro',
            name='valor_total_usd',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
