# Generated by Django 5.2.8 on 2025-12-08 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0012_documentoaprovacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentoaprovacao',
            old_name='observacao',
            new_name='comentario',
        ),
        migrations.RemoveField(
            model_name='documentoaprovacao',
            name='aprovado',
        ),
        migrations.AddField(
            model_name='documentoaprovacao',
            name='status',
            field=models.CharField(choices=[('aprovado', 'Aprovado'), ('revisar', 'Revisar'), ('reprovado', 'Reprovado')], default='revisar', max_length=50),
        ),
        migrations.AlterField(
            model_name='documentoaprovacao',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='pasta_base',
            field=models.CharField(help_text='Caminho base onde serão criadas as pastas GRDT/GED', max_length=500),
        ),
    ]
