# Generated by Django 5.2.8 on 2025-12-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0013_rename_observacao_documentoaprovacao_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='etapa_atual',
            field=models.CharField(choices=[('ELABORACAO', 'Documento em Elaboração'), ('REVISAO_INTERNA', 'Revisão Interna'), ('APROVACAO_TECNICA', 'Aprovação Técnica'), ('DOC_CONTROL', 'Doc Control'), ('ENVIADO_CLIENTE', 'Enviado ao Cliente'), ('APROVACAO_CLIENTE', 'Aprovação Cliente (PCF)'), ('EMISSAO_FINAL', 'Emissão Final')], default='ELABORACAO', max_length=100),
        ),
    ]
