# Generated by Django 5.2.8 on 2025-12-12 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documentos', '0014_alter_documento_etapa_atual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowetapa',
            options={'ordering': ['ordem'], 'verbose_name': 'Etapa de Workflow', 'verbose_name_plural': 'Etapas de Workflow'},
        ),
        migrations.RemoveField(
            model_name='documento',
            name='etapa_atual',
        ),
        migrations.AddField(
            model_name='documento',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='documentos.workflowetapa', verbose_name='Etapa atual do workflow'),
        ),
        migrations.AddField(
            model_name='workflowetapa',
            name='codigo',
            field=models.CharField(choices=[('ELABORACAO', 'Documento em Elaboração'), ('REVISAO_INTERNA', 'Revisão Interna'), ('APROVACAO_TECNICA', 'Aprovação Técnica'), ('DOC_CONTROL', 'Doc Control'), ('ENVIADO_CLIENTE', 'Enviado ao Cliente'), ('APROVACAO_CLIENTE', 'Aprovação Cliente (PCF)'), ('EMISSAO_FINAL', 'Emissão Final')], default='ELABORACAO', help_text='Identificador interno da etapa (ex: ELABORACAO, DOC_CONTROL).', max_length=50, verbose_name='Código técnico da etapa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflowetapa',
            name='proxima_etapa',
            field=models.ForeignKey(blank=True, help_text='Etapa de destino quando o documento é avançado a partir desta etapa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_anteriores', to='documentos.workflowetapa', verbose_name='Próxima etapa padrão'),
        ),
        migrations.AlterField(
            model_name='workflowetapa',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Etapa ativa?'),
        ),
        migrations.AlterField(
            model_name='workflowetapa',
            name='grupos_responsaveis',
            field=models.ManyToManyField(blank=True, help_text='Grupos de usuários que podem atuar nesta etapa (ex: Elaboradores).', to='auth.group', verbose_name='Grupos responsáveis pela etapa'),
        ),
        migrations.AlterField(
            model_name='workflowetapa',
            name='nome',
            field=models.CharField(help_text='Nome amigável exibido nas telas (ex: Documento em Elaboração).', max_length=100, verbose_name='Nome exibido da etapa'),
        ),
        migrations.AlterField(
            model_name='workflowetapa',
            name='ordem',
            field=models.PositiveIntegerField(help_text='1 = primeira etapa, 2 = segunda, etc.', verbose_name='Ordem no fluxo'),
        ),
        migrations.AlterField(
            model_name='workflowetapa',
            name='prazo_dias',
            field=models.PositiveIntegerField(default=15, help_text='SLA padrão em dias para esta etapa.', verbose_name='Prazo (dias)'),
        ),
        migrations.CreateModel(
            name='DocumentoWorkflowHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('AVANCAR', 'Avançar etapa'), ('RETORNAR', 'Retornar etapa'), ('AJUSTE_MANUAL', 'Ajuste manual')], max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_workflow', to='documentos.documento')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.workflowetapa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Workflow',
                'verbose_name_plural': 'Histórico de Workflow',
                'ordering': ['-data'],
            },
        ),
    ]
