# Generated by Django 5.2.8 on 2025-12-17 18:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0015_alter_workflowetapa_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoworkflowhistorico',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workflowetapa',
            name='codigo',
            field=models.CharField(choices=[('ELABORACAO', 'Documento em Elaboração'), ('REVISAO_INTERNA', 'Revisão Interna'), ('APROVACAO_TECNICA', 'Aprovação Técnica'), ('DOC_CONTROL', 'Doc Control'), ('ENVIADO_CLIENTE', 'Enviado ao Cliente'), ('APROVACAO_CLIENTE', 'Aprovação Cliente (PCF)'), ('EMISSAO_FINAL', 'Emissão Final')], help_text='Identificador interno da etapa (ex: ELABORACAO, DOC_CONTROL).', max_length=50, unique=True, verbose_name='Código técnico da etapa'),
        ),
        migrations.CreateModel(
            name='DocumentoWorkflowHistoricoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='workflow_anexos/%Y/%m/')),
                ('nome_original', models.CharField(blank=True, max_length=255, null=True)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='documentos.documentoworkflowhistorico')),
            ],
            options={
                'verbose_name': 'Anexo do Histórico do Workflow',
                'verbose_name_plural': 'Anexos do Histórico do Workflow',
                'ordering': ['-enviado_em'],
            },
        ),
    ]
