# Generated by Django 5.2.8 on 2025-12-17 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0016_alter_documentoworkflowhistorico_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='etapa_atual',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='WorkflowTransicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transicoes_destino', to='documentos.workflowetapa')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transicoes_origem', to='documentos.workflowetapa')),
            ],
            options={
                'verbose_name': 'Transição de Workflow',
                'verbose_name_plural': 'Transições de Workflow',
                'unique_together': {('origem', 'destino')},
            },
        ),
    ]
