# Generated by Django 5.2.8 on 2025-12-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0017_documento_etapa_atual_workflowtransicao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowtransicao',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='documento',
            name='etapa_atual',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documentoworkflowhistorico',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AddConstraint(
            model_name='workflowtransicao',
            constraint=models.UniqueConstraint(fields=('origem', 'destino'), name='uniq_transicao_origem_destino'),
        ),
    ]
