# Generated by Django 5.2.8 on 2026-08-13 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0018_alter_workflowtransicao_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoReferenciaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(choices=[('DOX', 'DOX'), ('KM', 'Kongsberg/KM'), ('CLIENTE', 'Cliente')], db_index=True, max_length=30)),
                ('identificador_externo', models.CharField(db_index=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('sincronizado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_externas', to='documentos.documento')),
            ],
            options={
                'ordering': ['sistema', 'identificador_externo'],
                'indexes': [models.Index(fields=['documento', 'sistema'], name='documentos__documen_8bdff8_idx')],
                'constraints': [models.UniqueConstraint(fields=('sistema', 'identificador_externo'), name='uniq_referencia_externa_sistema_id')],
            },
        ),
    ]
