# Generated by Django 5.2.8 on 2026-08-14 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0019_documentoreferenciaexterna'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoreferenciaexterna',
            name='conferido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoreferenciaexterna',
            name='divergencias',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='documentoreferenciaexterna',
            name='divergente',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='documentoreferenciaexterna',
            name='status_externo',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.CreateModel(
            name='DocumentoMestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200)),
                ('codigo_normalizado', models.CharField(db_index=True, max_length=220, unique=True)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('disciplina', models.CharField(blank=True, max_length=100)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('revisao_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mestres_como_revisao_atual', to='documentos.documento')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='mestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisoes', to='documentos.documentomestre'),
        ),
    ]
