from pathlib import Path

src=Path(r"D:\GED_PROFISSIONAL\tmp\enterprise_r12\dashboard_ref.html")
out=Path(r"D:\GED_PROFISSIONAL\outputs\pacote_diretoria_r12_enterprise\DASHBOARD_GESTAO_INTEGRADA_DOC_CONTROL_R14_ENTERPRISE.html")
s=src.read_text(encoding="utf-8")
s=s.replace("R11 Final", "R14 Enterprise - Escopo Separado")
old='<div class="actions"><button class="resource-btn" onclick="downloadEmbedded(\'xlsx\')"><span class="file-icon">XLSX</span><span class="button-copy"><small>Base auditável · R10</small><strong>Histograma completo</strong></span><span class="download-arrow">↓</span></button><button class="resource-btn ppt" onclick="downloadEmbedded(\'pptx\')"><span class="file-icon">PPTX</span><span class="button-copy"><small>Diretoria · R10</small><strong>Apresentação Enterprise</strong></span><span class="download-arrow">↓</span></button><button class="utility-btn" id="expandBtn">Memória técnica</button><button class="utility-btn primary" onclick="downloadEmbedded(\'pdf\')">Exportar PDF</button></div>'
new='<div class="actions"><a class="resource-btn" href="HISTOGRAMA_INTEGRADO_DOC_CONTROL_ARQUIVO_TECNICO_R12_ENTERPRISE.xlsx"><span class="file-icon">XLSX</span><span class="button-copy"><small>Base auditável · R12</small><strong>Histograma integrado</strong></span><span class="download-arrow">↓</span></a><a class="resource-btn ppt" href="APRESENTACAO_EXECUTIVA_GESTAO_INTEGRADA_R12_ENTERPRISE.pptx"><span class="file-icon">PPTX</span><span class="button-copy"><small>Diretoria · R12</small><strong>Apresentação Enterprise</strong></span><span class="download-arrow">↓</span></a><button class="utility-btn" id="expandBtn">Memória técnica</button><a class="utility-btn primary" href="RELATORIO_EXECUTIVO_GESTAO_INTEGRADA_R12_ENTERPRISE.pdf">Abrir PDF</a></div>'
s=s.replace(old,new)
s=s.replace("Formalizar a Gestão Integrada de Document Control do portfólio naval", "Formalizar a governança integrada e recalibrar o custo consolidado")
s=s.replace("O business case propõe uma <strong>governança transversal para três contratos</strong>, suportada por uma baseline otimizada, capacidade técnica crítica preservada e mecanismos objetivos de revisão quando as premissas operacionais mudarem.", "A separação entre Doc Control e Arquivo Técnico organiza responsabilidades, mas o custo total permanece praticamente no nível acordado. A redução deve ser medida no consolidado dos dois setores e atingir <strong>20% ou mais</strong>.")
oldk='<div class="kpis"><article class="kpi glass" style="--a:var(--mint)" data-memory="economia"><div class="label">Economia total</div><div class="num">R$ 3,62 mi</div><div class="sub">cenário completo × reduzido</div><div class="kpi-hint"><i>+</i>Ver memória</div></article><article class="kpi glass" style="--a:var(--cyan)" data-memory="custo"><div class="label">Redução de custo</div><div class="num">49,7%</div><div class="sub">R$ 7,29 mi → R$ 3,67 mi</div><div class="kpi-hint"><i>+</i>Ver memória</div></article><article class="kpi glass" style="--a:var(--amber)" data-memory="hm"><div class="label">Redução de HM</div><div class="num">58,2%</div><div class="sub">1.028,5 → 429,5 HM</div><div class="kpi-hint"><i>+</i>Ver memória</div></article><article class="kpi glass" style="--a:#9a83ff" data-memory="hh"><div class="label">HH economizadas</div><div class="num">131.780</div><div class="sub">premissa 220 HH/HM</div><div class="kpi-hint"><i>+</i>Ver memória</div></article><article class="kpi glass" style="--a:var(--danger)" data-memory="pico"><div class="label">Pico reduzido</div><div class="num">9 MOI</div><div class="sub">completo: 23 MOI</div><div class="kpi-hint"><i>+</i>Ver memória</div></article></div>'
newk='<div class="kpis"><article class="kpi glass" style="--a:var(--cyan)"><div class="label">Custo acordado</div><div class="num">R$ 7,290 mi</div><div class="sub">baseline original</div></article><article class="kpi glass" style="--a:var(--amber)"><div class="label">Custo separado</div><div class="num">R$ 7,291 mi</div><div class="sub">Doc Control + Arquivo</div></article><article class="kpi glass" style="--a:var(--danger)"><div class="label">Redução consolidada</div><div class="num">≈ 0,0%</div><div class="sub">meta da Diretoria ≥ 20%</div></article><article class="kpi glass" style="--a:#9a83ff"><div class="label">HM separado</div><div class="num">1.113,5</div><div class="sub">+85 HM vs. acordado</div></article><article class="kpi glass" style="--a:var(--danger)"><div class="label">Gap para a meta</div><div class="num">R$ 1,459 mi</div><div class="sub">redução adicional necessária</div></article></div>'
s=s.replace(oldk,newk)
s=s.replace('<div class="benchmark-grid"><article class="benchmark glass current"><div class="eyebrow">Gestão atual · PJ</div><div class="money">R$ 11.000</div><p class="intro">Referência atual de Gestão Doc Control.</p></article><article class="benchmark glass"><div class="eyebrow">Supervisor Niterói · CLT</div><div class="money">R$ 11.850</div><p class="intro">Gestão atual é 7,2% menor no custo empresa.</p></article><article class="benchmark glass"><div class="eyebrow">Supervisor RG · CLT</div><div class="money">R$ 14.670</div><p class="intro">Gestão atual é 25,0% menor no custo empresa.</p></article></div>', '<div class="benchmark-grid" style="grid-template-columns:repeat(4,1fr)"><article class="benchmark glass current"><div class="eyebrow">Gestão atual · PJ</div><div class="money">R$ 11.000</div><p class="intro">Governança transversal proposta.</p></article><article class="benchmark glass"><div class="eyebrow">Supervisor Niterói · CLT</div><div class="money">R$ 11.850</div><p class="intro">Gestão PJ é R$ 850/mês menor.</p></article><article class="benchmark glass"><div class="eyebrow">Supervisor GLP / RG · CLT</div><div class="money">R$ 14.670</div><p class="intro">Gestão PJ é R$ 3.670/mês menor.</p></article><article class="benchmark glass"><div class="eyebrow">Duas supervisões locais</div><div class="money">R$ 26.520</div><p class="intro">Gestão PJ é R$ 15.520/mês (58,5%) menor.</p></article></div>')
out.parent.mkdir(parents=True,exist_ok=True);out.write_text(s,encoding="utf-8")
print(out, out.stat().st_size)
